name: Trigger Automation for Docker update

on:
  repository_dispatch:
    types: [build-release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up bashbrew
        uses: docker-library/bashbrew@v0.1.12
      
      - name: Check if bashbrew in installed
        run: |
          bashbrew --version

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Validate Payload
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format. Expected format: x.y.z"
            exit 1
          fi
      
      - name: Create new version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          